// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {downloader} from '../models';

export function DownloadSubtitle(arg1:string,arg2:string,arg3:string):Promise<void>;

export function DownloadSubtitleWithFormat(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function DownloadVideo(arg1:string,arg2:string):Promise<void>;

export function DownloadVideoWithFormat(arg1:string,arg2:string,arg3:string):Promise<void>;

export function FetchAvailableFormats(arg1:string):Promise<Array<downloader.FormatOption>>;

export function FetchAvailableSubtitles(arg1:string):Promise<Array<downloader.SubtitleOption>>;

export function GetMediaURL():Promise<string>;

export function LoadSubtitle():Promise<string>;

export function SelectDirectory():Promise<string>;

export function SelectVideoFile():Promise<string>;

export function ValidateURL(arg1:string):Promise<void>;
