// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetMediaURL():Promise<string>;

export function LoadSubtitle():Promise<string>;

export function SelectVideoFile():Promise<string>;
