// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DownloadSubtitle(arg1, arg2, arg3) {
  return window['go']['app']['App']['DownloadSubtitle'](arg1, arg2, arg3);
}

export function DownloadSubtitleWithFormat(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['DownloadSubtitleWithFormat'](arg1, arg2, arg3, arg4);
}

export function DownloadVideo(arg1, arg2) {
  return window['go']['app']['App']['DownloadVideo'](arg1, arg2);
}

export function DownloadVideoWithFormat(arg1, arg2, arg3) {
  return window['go']['app']['App']['DownloadVideoWithFormat'](arg1, arg2, arg3);
}

export function FetchAvailableFormats(arg1) {
  return window['go']['app']['App']['FetchAvailableFormats'](arg1);
}

export function FetchAvailableSubtitles(arg1) {
  return window['go']['app']['App']['FetchAvailableSubtitles'](arg1);
}

export function GetMediaURL() {
  return window['go']['app']['App']['GetMediaURL']();
}

export function HasWhisper() {
  return window['go']['app']['App']['HasWhisper']();
}

export function LoadSubtitle() {
  return window['go']['app']['App']['LoadSubtitle']();
}

export function SelectDirectory() {
  return window['go']['app']['App']['SelectDirectory']();
}

export function SelectVideoFile() {
  return window['go']['app']['App']['SelectVideoFile']();
}

export function SpeakEdgeTTS(arg1, arg2) {
  return window['go']['app']['App']['SpeakEdgeTTS'](arg1, arg2);
}

export function ValidateURL(arg1) {
  return window['go']['app']['App']['ValidateURL'](arg1);
}
