// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetMediaURL() {
  return window['go']['app']['App']['GetMediaURL']();
}

export function LoadSubtitle() {
  return window['go']['app']['App']['LoadSubtitle']();
}

export function SelectVideoFile() {
  return window['go']['app']['App']['SelectVideoFile']();
}
